sudo: false
language: python
python:
  - 3.5
env:
  matrix:
    # note: please use "tox --listenvs" to populate the build matrix below
    - TOXENV=linting
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py36
    - TOXENV=py27-pexpect
    - TOXENV=py27-xdist
    - TOXENV=py27-trial
    - TOXENV=py27-numpy
    - TOXENV=py36-pexpect
    - TOXENV=py36-xdist
    - TOXENV=py36-trial
    - TOXENV=py36-numpy
    - TOXENV=py27-nobyte
    - TOXENV=doctesting
    - TOXENV=docs

matrix:
  include:
    - env: TOXENV=py26
      python: '2.6'
    - env: TOXENV=py33
      python: '3.3'
    - env: TOXENV=pypy
      python: 'pypy-5.4'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py35-freeze
      python: '3.5'
    - env: TOXENV=py37
      python: 'nightly'
  allow_failures:
    - env: TOXENV=py37
      python: 'nightly'

install: "pip install -U devpi"
script:
  - devpi use $DEVPI_INDEX
  - devpi test $PACKAGE==$VERSION
